import React, { useState } from 'react'
import './HIFI.scss'

const HIFI = () => {
  const [showContent, setShowContent] = useState()
  const [inputData, setInputData] = useState({
    name: '',
    email: '',
    text: '',
  })
  const [contentArr, setContentArr] = useState([
    {
      id: 1,
      heading: 'What is Copy Trading and how does it work with Universal FX?',
      content:
        'Copy Trading is a strategy that allows you to replicate the trades of experienced traders. At Universal FX, you grant authority to our Copy Trader Masters, who will trade on your behalf. Their trades are mirrored in your account, enabling you to benefit from their expertise and strategies without having to trade manually.',
      status: false,
    },
    {
      id: 2,
      heading: 'What types of income can I earn with Universal FX?',
      content:
        'With Universal FX, you can earn two types of income: Individual Earnings and Referral Commissions. Individual Earnings come from the profits generated by copying the trades of our expert traders. Referral Commissions are earned by referring others to the platform, with 10% commission on direct referrals and 5% on indirect referrals.',
      status: false,
    },
    {
      id: 3,
      heading: ' How do I start Copy Trading with Universal FX?',
      content:
        'Copy Trading is a strategy that allows you to replicate the trades of experienced traders. At Universal FX, you grant authority to our Copy Trader Masters, who will trade on your behalf. Their trades are mirrored in your account, enabling you to benefit from their expertise and strategies without having to trade manually.',
      status: false,
    },
  ])
  const handleContentDisplay = (id) => {
    const filteredData = contentArr.map((data) =>
      data.id === id ? { ...data, status: true } : data
    )
    setContentArr(filteredData)
  }
  const handleHideContent = (id) => {
    const filteredData = contentArr.map((data) =>
      data.id === id ? { ...data, status: false } : data
    )
    setContentArr(filteredData)
  }
  const handleFormSubmit = async () => {}

  return (
    <section className="HIFI">
      <div className="HIFI-container">
        <div className="heading">
          <h2>Any Questions? We’ve Got You!</h2>
        </div>
        <main className="content">
          <section className="content-wrapper">
            {contentArr.map((data) => {
              const { heading, content, status, id } = data
              return (
                <article key={id} className="content-box">
                  <img src="/ph_question-fill.svg" alt="question" />
                  <div>
                    <h3 className="content-heading">{heading}</h3>
                    {status && <p className="paragraph">{content}</p>}
                  </div>
                  {status ? (
                    <img
                      src="/outline_down.svg"
                      alt="down-icon"
                      onClick={() => handleHideContent(id)}
                    />
                  ) : (
                    <img
                      src="/outline_up.svg"
                      alt="down-icon"
                      onClick={() => handleContentDisplay(id)}
                    />
                  )}
                </article>
              )
            })}
          </section>
          <section className="contact-us">
            <h2 className="contact-heading">Contact Us</h2>
            <form className="contact-form" onSubmit={handleFormSubmit}>
              <input
                type="text"
                placeholder="Your name"
                className="input"
                value={inputData.name}
                onChange={(e) =>
                  setInputData({ ...inputData, name: e.target.value })
                }
              />
              <input
                type="email"
                placeholder="Your email"
                className="input"
                value={inputData.email}
                onChange={(e) =>
                  setInputData({ ...inputData, email: e.target.value })
                }
              />
              <textarea
                placeholder="Your message"
                className="textarea"
                value={inputData.text}
                onChange={(e) =>
                  setInputData({ ...inputData, text: e.target.value })
                }
              ></textarea>
              <div className="contact-btn">
                <button type="submit" className="button">
                  Submit
                </button>
              </div>
            </form>
          </section>
        </main>
      </div>
      <footer className="footer">
        <div>
          <section className="footer-wrapper">
            <article>
              <h2>Company</h2>
              <p>About us</p>
              <p>Contact us</p>
              <p>Careers</p>
              <p>Press</p>
            </article>
            <article>
              <h2>Product</h2>
              <p>Features</p>
              <p>Pricing</p>
              <p>News</p>
              <p>Help desk</p>
              <p>Support</p>
            </article>
            <article>
              <h2>Services</h2>
              <p>copy Trading</p>
              <p>Trading Signals</p>
              <p>Risk</p>
              <p>Management</p>
            </article>
            <article>
              <h2>Legal</h2>
              <p>Privacy Policy</p>
              <p>Terms &</p>
              <p>Conditions</p>
            </article>
            <article>
              <h2>Contact Us</h2>
              <p>support@universalfx.site</p>
            </article>
          </section>
          <section className="social">
            <hr />
            <div className="social-media-wrapper">
              <p>© 2024 Copyright, All Right Reserved, Universal FX</p>
              <div className="social-media">
                <img src="/Social.svg" alt="social" />
              </div>
            </div>
          </section>
        </div>
      </footer>
    </section>
  )
}

export default HIFI
